description: >
  Executor for terraform.
docker:
  - image: "550842621181.dkr.ecr.us-east-1.amazonaws.com/pipeline-image:<<parameters.tag>>"
resource_class: large
parameters:
  tag:
    default: latest
    description: >
      Executor Image tag to use for the build
    type: string
